version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 3031:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: php_dockerfile
    ports:
      - 3032:9000
    volumes:
      - ./src:/usr/share/nginx/html
    depends_on:
      - db

  db:
    image: mysql:5.6
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3033:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 3034:80
    depends_on:
      - db
